//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CustomsCloud.CRM.CertificateOfOrigins.BL {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ErrorMessagesResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorMessagesResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CustomsCloud.CRM.CertificateOfOrigins.BL.ErrorMessagesResources", typeof(ErrorMessagesResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TODO(text) UIMessage 6541 — AdditionalCertificatesToExportDeclaration {0}.
        /// </summary>
        internal static string AdditionalCertificatesToExportDeclaration {
            get {
                return ResourceManager.GetString("AdditionalCertificatesToExportDeclaration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TODO(text) ServerTerm 5245 — CanceledDeclaration.
        /// </summary>
        internal static string CanceledDeclaration {
            get {
                return ResourceManager.GetString("CanceledDeclaration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TODO(text) UIMessage 14026542 — CertificateNumberISNotMatchToCerrtificateNumberInExportDealFile.
        /// </summary>
        internal static string CertificateNumberIsNotMatchToCertificateNumberInExportDealFile {
            get {
                return ResourceManager.GetString("CertificateNumberIsNotMatchToCertificateNumberInExportDealFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TODO(text) UIMessage 6545 — CertificateReplaced {0}.
        /// </summary>
        internal static string CertificateReplaced {
            get {
                return ResourceManager.GetString("CertificateReplaced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TODO(text) UIMessage 14027278 — CustomsItemInDeclarationIsNotMAtchToCustomsItemsInCertificate {0} {1}.
        /// </summary>
        internal static string CustomsItemInDeclarationIsNotMatchToCustomsItemsInCertificate {
            get {
                return ResourceManager.GetString("CustomsItemInDeclarationIsNotMatchToCustomsItemsInCertificate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TODO(text) UIMessage 14026547 — CustomsItemIsNotMAtchToCustomsItemInExportdeclaration {0} {1}.
        /// </summary>
        internal static string CustomsItemIsNotMatchToCustomsItemInExportDeclaration {
            get {
                return ResourceManager.GetString("CustomsItemIsNotMatchToCustomsItemInExportDeclaration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TODO(text) UIMessage 1402655 — DestinationCountryIsNotMAtchTofDestinationCountryInExportdeclaration.
        /// </summary>
        internal static string DestinationCountryIsNotMatchToDestinationCountryInExportDeclaration {
            get {
                return ResourceManager.GetString("DestinationCountryIsNotMatchToDestinationCountryInExportDeclaration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TODO(text) UIMessage 14027170 — DiscrepancyBetweenTheCountriesInTheAgreementVersusTheCountryOfTheBuyer.
        /// </summary>
        internal static string DiscrepancyBetweenTheCountriesInTheAgreementVersusTheCountryOfTheBuyer {
            get {
                return ResourceManager.GetString("DiscrepancyBetweenTheCountriesInTheAgreementVersusTheCountryOfTheBuyer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TODO(text) UIMessage 14026636 — ExportDeclarationNotInSystemForWarningMessage {0}.
        /// </summary>
        internal static string ExportDeclarationNotInSystemForWarningMessage {
            get {
                return ResourceManager.GetString("ExportDeclarationNotInSystemForWarningMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TODO(text) UIMessage 14026543 — ExporterNumberIsNotMAtchToExporterNumberInExportdeclaration.
        /// </summary>
        internal static string ExporterNumberIsNotMatchToExporterNumberInExportDeclaration {
            get {
                return ResourceManager.GetString("ExporterNumberIsNotMatchToExporterNumberInExportDeclaration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TODO(text) UIMessage 14026546 — ExportInvoiceIsNotMAtchToExportInvoiceInExportdeclaration {0}.
        /// </summary>
        internal static string ExportInvoiceIsNotMatchToExportInvoiceInExportDeclaration {
            get {
                return ResourceManager.GetString("ExportInvoiceIsNotMatchToExportInvoiceInExportDeclaration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TODO(text) UIMessage 14026704 — MessageToAgentCertificateOfOrigin {0} {1}.
        /// </summary>
        internal static string MessageToAgentCertificateOfOrigin {
            get {
                return ResourceManager.GetString("MessageToAgentCertificateOfOrigin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TODO(text) UIMessage 1402654 — OriginCountryIsNotMAtchToOriginCountryInExportdeclaration.
        /// </summary>
        internal static string OriginCountryIsNotMatchToOriginCountryInExportDeclaration {
            get {
                return ResourceManager.GetString("OriginCountryIsNotMatchToOriginCountryInExportDeclaration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TODO(text) UIMessage 14027187 — ThereIsNoMerchandiseInTheDeclarationThatIsLinkedToTheImportDeclarationWhoseCountryOfOriginIsInTheTradeAgreement.
        /// </summary>
        internal static string ThereIsNoMerchandiseLinkedToImportDeclarationInTradeAgreement {
            get {
                return ResourceManager.GetString("ThereIsNoMerchandiseLinkedToImportDeclarationInTradeAgreement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TODO(text) UIMessage 6544 — UpdateExportDecForReplacement {0} {1} {2}.
        /// </summary>
        internal static string UpdateExportDecForReplacement {
            get {
                return ResourceManager.GetString("UpdateExportDecForReplacement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TODO(text) UIMessage 6540 — UpdateExportDeclaration {0} {1}.
        /// </summary>
        internal static string UpdateExportDeclaration {
            get {
                return ResourceManager.GetString("UpdateExportDeclaration", resourceCulture);
            }
        }
    }
}
