IF SCHEMA_ID(N'CRM') IS NULL EXEC(N'CREATE SCHEMA CRM');
GO

IF SCHEMA_ID(N'dbo') IS NULL EXEC(N'CREATE SCHEMA dbo');
GO

IF SCHEMA_ID(N'Shared') IS NULL EXEC(N'CREATE SCHEMA Shared');

GO
IF TYPE_ID('Shared.IntArray') IS NULL
    CREATE TYPE Shared.IntArray AS TABLE ([val] INT);
GO